import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY BUN
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = Bun.argv.includes('production');

const result = await Bun.build({
	entrypoints: ['src/main.ts'],
	outdir: '.',
	naming: 'main.js',
	format: 'cjs',
	target: 'browser',
	minify: prod,
	sourcemap: prod ? 'none' : 'inline',
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	banner,
});

if (!result.success) {
	console.error('Build failed:');
	for (const log of result.logs) {
		console.error(log);
	}
	process.exit(1);
}

console.log(`Build ${prod ? 'production' : 'development'} completed successfully!`);
